services:
  - type: web
    name: online-classroom
    runtime: python
    buildCommand: ""
    startCommand: gunicorn app:app --bind 0.0.0.0:10000
    envVars:
      - key: FLASK_ENV
        value: production
